name: hwtest_adam_fauzan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_iconly: ^1.0.2
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.5
  get: ^4.6.5
  get_storage: ^2.1.1
  shimmer: ^2.0.0
  sizer: ^2.0.15
  persistent_bottom_nav_bar: ^6.2.1
  carousel_slider_plus: ^7.1.0

dev_dependencies:
  build_runner: 
  flutter_gen_runner: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_gen:
  output: lib/resources/

flutter:
  uses-material-design: true
  assets:
    - lib/resources/images/
